apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  labels:
    app: next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: devbreed/next-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: next-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: next
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005

      nodePort: 31100