apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  labels:
    app: next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
      - name: next
        image: nextimage
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: next-service
spec:
  type: NodePort
  selector:
    app: next
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
      nodePort: 31100